// Countries list for contact form dropdown
export const COUNTRIES = [
    { label: 'India', value: 'IN' },
    { label: 'United States', value: 'US' },
    { label: 'United Kingdom', value: 'GB' },
    { label: 'Canada', value: 'CA' },
    { label: 'Australia', value: 'AU' },
    { label: 'United Arab Emirates', value: 'AE' },
    { label: 'Singapore', value: 'SG' },
    { label: 'Germany', value: 'DE' },
    { label: 'France', value: 'FR' },
    { label: 'Japan', value: 'JP' },
    { label: 'China', value: 'CN' },
    { label: 'South Korea', value: 'KR' },
    { label: 'Brazil', value: 'BR' },
    { label: 'Mexico', value: 'MX' },
    { label: 'Spain', value: 'ES' },
    { label: 'Italy', value: 'IT' },
    { label: 'Netherlands', value: 'NL' },
    { label: 'Switzerland', value: 'CH' },
    { label: 'Sweden', value: 'SE' },
    { label: 'Norway', value: 'NO' },
    { label: 'Denmark', value: 'DK' },
    { label: 'Belgium', value: 'BE' },
    { label: 'Austria', value: 'AT' },
    { label: 'New Zealand', value: 'NZ' },
    { label: 'South Africa', value: 'ZA' },
    { label: 'Saudi Arabia', value: 'SA' },
    { label: 'Qatar', value: 'QA' },
    { label: 'Kuwait', value: 'KW' },
    { label: 'Bahrain', value: 'BH' },
    { label: 'Oman', value: 'OM' },
    { label: 'Malaysia', value: 'MY' },
    { label: 'Thailand', value: 'TH' },
    { label: 'Indonesia', value: 'ID' },
    { label: 'Philippines', value: 'PH' },
    { label: 'Vietnam', value: 'VN' },
    { label: 'Bangladesh', value: 'BD' },
    { label: 'Pakistan', value: 'PK' },
    { label: 'Sri Lanka', value: 'LK' },
    { label: 'Nepal', value: 'NP' },
    { label: 'Other', value: 'OTHER' }
];
